server:
  port: 1002
security:
  jwt:
    expiration: ${SECURITY_JWT_EXPIRATION:#{8*60*60}}
    header: ${SECURITY_JWT_HEADER:Authorization}
    prefix: ${SECURITY_JWT_PREFIX:Bearer }
    secret: ${SECURITY_JWT_SECRET:JwtSecretKey}
    uri: ${SECURITY_JWT_EXPIRATION:/login}
app:
  param-config:
    pass-simple: 123456aA@
    login:
      key: tunglm
spring:
  application:
    name: LTS Platform
    company: LTS Group
    team: Java Team
  datasource:
    jdbc-url: jdbc:mysql://172.16.8.27:3307/lts-test?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ltslqa
    driver-class-name: com.mysql.cj.jdbc.Driver
    minimum-idle: 1
    maximum-pool-size: 10
    auto-commit: false
    connection-timeout: 600000
    idle-timeout: 600000
    max-lifetime: 1800000
    validation-timeout: 600000
    leak-detection-threshold: 100000
    pool-name: Pool-lts
    data-source-properties: v$session.program=LTS-PLATFORM
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

#Config log lever view tại console + log4j
#logging:
#  config: config/log4j2.xml